from PyQt5.QtWidgets import QApplication, QWidget, QVBoxLayout, QPushButton, QFileDialog, QLabel, QTextEdit, QMainWindow
from PyQt5.QtGui import QPixmap
from PyQt5 import QtCore, QtGui, QtWidgets
import numpy as np
import cv2
import os
import sys
import torch
from numpy import *
import copy
import PySimpleGUI as sg
from PIL import Image
from torch.autograd import Variable
import torch.nn.functional as F
import torch.nn as nn
import torchvision.transforms as transforms

class Ui_MainWindow(object):
    imagePath = " "

    def backtoMain(self):
        self.stackedWidget.setCurrentIndex(0)
    def Preprocessing(self):
        self.stackedWidget.setCurrentIndex(1)
    def Classifier(self):
        self.stackedWidget.setCurrentIndex(2)
    def Tutorial1(self):
        self.stackedWidget.setCurrentIndex(3)
    def Tutorial2(self):
        self.stackedWidget.setCurrentIndex(4)
    def Tutorial3(self):
        self.stackedWidget.setCurrentIndex(5)

    def uploadimage(self):
            fname, _filter = QtWidgets.QFileDialog.getOpenFileName(None, "Open Image", '.', "(*.jpg *.png)")
            self.imagePath = fname
            if self.imagePath == '':
                    (self.ImageView.setPixmap(QPixmap("Pic/ER1.png")))
            else:
                    img = cv2.imread(self.imagePath)
                    cv2.imwrite('FruitImage.jpg', img)
                    self.ImageView.setPixmap(QPixmap('FruitImage.jpg'))
                    self.image_PP.setPixmap(QPixmap('FruitImage.jpg'))
                    self.ImageView2.setPixmap(QPixmap('FruitImage.jpg'))
    def removeimage(self):
        self.ImageView.setText(" ")
        self.image_PP.setText(" ")
        self.Image_PPout.setText(" ")
        self.ImageView2.setText(" ")
        if os.path.isfile('FruitImage.jpg'):
            os.remove('FruitImage.jpg')
        else:
            self.imagePath = " "

    def resizeimg(self):
            if self.imagePath == " ":
                    (self.image_PP.setPixmap(QPixmap("Pic/ER1.png")))
            else:
                    img = cv2.imread('FruitImage.jpg')
                    res = cv2.resize(img, (64, 64))
                    cv2.imwrite(self.imagePath, res)
                    self.Image_PPout.setPixmap(QPixmap('FruitImage.jpg'))

    def contrast(self):
            if self.imagePath == " ":
                    (self.image_PP.setPixmap(QPixmap("Pic/ER1.png")))
            else:
                    img = cv2.imread('FruitImage.jpg', cv2.IMREAD_COLOR)
                    norm_img1 = cv2.normalize(img, None, alpha=0, beta=1, norm_type=cv2.NORM_MINMAX, dtype=cv2.CV_32F)
                    norm_img2 = (255 * norm_img1).astype(np.uint8)
                    cv2.imwrite('FruitImage.jpg', norm_img2)
                    self.Image_PPout.setPixmap(QPixmap('FruitImage.jpg'))
    def median(self):
            if self.imagePath == " ":
                    (self.image_PP.setPixmap(QPixmap("Pic/ER1.png")))
            else:
                    img = cv2.imread('FruitImage.jpg')
                    median = cv2.medianBlur(img, 5)
                    cv2.imwrite('FruitImage.jpg', median)
                    self.Image_PPout.setPixmap(QPixmap('FruitImage.jpg'))
    def clear1(self):
            self.image_PP.setText(" ")
            self.Image_PPout.setText(" ")
    def nexttoclass(self):
        self.stackedWidget.setCurrentIndex(2)
        self.ImageView2.setPixmap(QPixmap('FruitImage.jpg'))
    def predict(self):
            if os.path.isfile('FruitImage.jpg'):
                    classes = (
                    'freshapple', 'freshbanana', 'freshorange', 'rottenapple', 'rottenbanana', 'rottenorange')
                    transform = transforms.Compose([transforms.Resize((64, 64)), transforms.ToTensor(),
                                                    transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))])

                    def image_loader(image_name):
                            """load image, returns tensor"""
                            image = Image.open(image_name).convert('RGB')  #load an image
                            image = transform(image).float()  #apply transformation
                            image = Variable(image, requires_grad=True)  #Convert to tensor
                            image = image.unsqueeze(0)
                            return image

                    class CNN(nn.Module):
                            def __init__(self):
                                    super(CNN, self).__init__()
                                    self.conv1 = nn.Conv2d(3, 32, 3)
                                    self.pool = nn.MaxPool2d(2, 2)
                                    self.conv2 = nn.Conv2d(32, 64, 3)
                                    self.fc1 = nn.Linear(64 * 14 * 14, 40)
                                    self.fc2 = nn.Linear(40, 6)

                            def forward(self, x):
                                    x = self.pool(F.relu(self.conv1(x)))
                                    x = self.pool(F.relu(self.conv2(x)))
                                    x = x.view(-1, 64 * 14 * 14)
                                    x = self.fc1(x)
                                    x = F.relu(x)
                                    x = self.fc2(x)
                                    return x

                    model = CNN()
                    # print(model)
                    state_dict = torch.load('Model/freshfruitmodel.pth')['state_dict']
                    model.load_state_dict(state_dict)
                    # change this path according to your image path
                    image = image_loader("FruitImage.jpg")
                    output = model(image)
                    # print(output.data.cpu().numpy()) #HIGHEST CONFIDENCE
                    _, predicted = torch.max(output, 1)
                    w = classes[predicted]
                    self.prediction.setText(w)

            else:
                    (self.ImageView2.setPixmap(QPixmap("Pic/ER1.png")))
    def clear2(self):
        self.ImageView2.setText(" ")
        self.prediction.setText(" ")


    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(873, 599)
        MainWindow.setMinimumSize(873, 599)
        MainWindow.setMaximumSize(873, 599)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Pic/2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 871, 601))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.stackedWidget.setFont(font)
        self.stackedWidget.setStyleSheet("background-color: rgb(234, 234, 234); ")
        self.stackedWidget.setObjectName("stackedWidget")
        self.Mian = QtWidgets.QWidget()
        self.Mian.setObjectName("Mian")
        self.groupBox_side1 = QtWidgets.QGroupBox(self.Mian)
        self.groupBox_side1.setGeometry(QtCore.QRect(-10, 100, 271, 511))
        self.groupBox_side1.setStyleSheet("background-color:rgb(34,139,34)")
        self.groupBox_side1.setTitle("")
        self.groupBox_side1.setObjectName("groupBox_side1")
        self.BtnPP = QtWidgets.QPushButton(self.groupBox_side1)
        self.BtnPP.setGeometry(QtCore.QRect(30, 190, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(11)
        self.BtnPP.setFont(font)
        self.BtnPP.setStyleSheet("QPushButton {  background-color: rgb(234, 234, 234);   border-radius:12px;}\n"
"QPushButton:pressed {background-color: rgb(189, 213, 234); border-radius:12px; }")
        self.BtnPP.setObjectName("BtnPP")
        self.BtnPP.clicked.connect(self.Preprocessing)
        self.BtnClass = QtWidgets.QPushButton(self.groupBox_side1)
        self.BtnClass.setGeometry(QtCore.QRect(30, 270, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(11)
        self.BtnClass.setFont(font)
        self.BtnClass.setStyleSheet("QPushButton {  background-color: rgb(234, 234, 234);   border-radius:12px;}\n"
"QPushButton:pressed {background-color: rgb(189, 213, 234); border-radius:12px; }")
        self.BtnClass.setObjectName("BtnClass")
        self.BtnClass.clicked.connect(self.Classifier)
        self.pushButton = QtWidgets.QPushButton(self.groupBox_side1)
        self.pushButton.setGeometry(QtCore.QRect(230, 470, 31, 23))
        self.pushButton.setStyleSheet("QPushButton {  background-color: rgb(234, 234, 234);   border-radius:5px;}\n"
"QPushButton:pressed {background-color: rgb(189, 213, 234); border-radius:5px; }")
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.Tutorial1)
        self.label_7 = QtWidgets.QLabel(self.Mian)
        self.label_7.setGeometry(QtCore.QRect(260, 100, 611, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setFrameShape(QtWidgets.QFrame.Box)
        self.label_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_7.setLineWidth(3)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.Header1 = QtWidgets.QLabel(self.Mian)
        self.Header1.setGeometry(QtCore.QRect(0, 0, 871, 101))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Header1.setFont(font)
        self.Header1.setStyleSheet("color: rgb(251, 248, 255);\n"
"background-color: rgb(34,139,34)")
        self.Header1.setFrameShape(QtWidgets.QFrame.Panel)
        self.Header1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Header1.setLineWidth(6)
        self.Header1.setAlignment(QtCore.Qt.AlignCenter)
        self.Header1.setObjectName("Header1")
        self.Logo1 = QtWidgets.QLabel(self.Mian)
        self.Logo1.setGeometry(QtCore.QRect(10, 10, 91, 81))
        self.Logo1.setStyleSheet("background-color: rgb(34,139,34)")
        self.Logo1.setText("")
        self.Logo1.setPixmap(QtGui.QPixmap("Pic/2.png"))
        self.Logo1.setScaledContents(True)
        self.Logo1.setObjectName("Logo1")
        self.ImageView = QtWidgets.QLabel(self.Mian)
        self.ImageView.setGeometry(QtCore.QRect(560, 250, 261, 251))
        self.ImageView.setFrameShape(QtWidgets.QFrame.Panel)
        self.ImageView.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.ImageView.setLineWidth(2)
        self.ImageView.setScaledContents(True)
        self.ImageView.setText("")
        self.ImageView.setObjectName("ImageView")
        self.label_3 = QtWidgets.QLabel(self.Mian)
        self.label_3.setGeometry(QtCore.QRect(360, 260, 121, 111))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("Pic/8.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.Btn_Upload = QtWidgets.QPushButton(self.Mian)
        self.Btn_Upload.setGeometry(QtCore.QRect(350, 390, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(8)
        self.Btn_Upload.setFont(font)
        self.Btn_Upload.setStyleSheet("QPushButton {color: rgb(251, 248, 255);\n"
"background-color: rgb(34,139,34);border-radius:10px;}\n"
"QPushButton:pressed { background-color: rgb(189, 213, 234); border-radius:10px; ;}")
        self.Btn_Upload.setObjectName("Btn_Upload")
        self.Btn_Upload.clicked.connect(self.uploadimage)
        self.Btn_remove = QtWidgets.QPushButton(self.Mian)
        self.Btn_remove.setGeometry(QtCore.QRect(350, 450, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(8)
        self.Btn_remove.setFont(font)
        self.Btn_remove.setStyleSheet("QPushButton {color: rgb(251, 248, 255);\n"
"background-color: rgb(34,139,34);border-radius:10px;}\n"
"QPushButton:pressed { background-color: rgb(189, 213, 234); border-radius:10px; ;}")
        self.Btn_remove.setObjectName("Btn_remove")
        self.Btn_remove.clicked.connect(self.removeimage)
        self.Image = QtWidgets.QLabel(self.Mian)
        self.Image.setGeometry(QtCore.QRect(560, 220, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.Image.setFont(font)
        self.Image.setStyleSheet("color: rgb(251, 248, 255);\n"
"background-color: rgb(34,139,34)")
        self.Image.setFrameShape(QtWidgets.QFrame.Panel)
        self.Image.setFrameShadow(QtWidgets.QFrame.Plain)
        self.Image.setLineWidth(2)
        self.Image.setAlignment(QtCore.Qt.AlignCenter)
        self.Image.setObjectName("Image")
        self.stackedWidget.addWidget(self.Mian)
        self.pre = QtWidgets.QWidget()
        self.pre.setObjectName("pre")
        self.Header2 = QtWidgets.QLabel(self.pre)
        self.Header2.setGeometry(QtCore.QRect(0, 0, 871, 101))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Header2.setFont(font)
        self.Header2.setStyleSheet("color: rgb(251, 248, 255);\n"
"background-color: rgb(34,139,34)")
        self.Header2.setFrameShape(QtWidgets.QFrame.Panel)
        self.Header2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Header2.setLineWidth(6)
        self.Header2.setAlignment(QtCore.Qt.AlignCenter)
        self.Header2.setObjectName("Header2")
        self.Logo2 = QtWidgets.QLabel(self.pre)
        self.Logo2.setGeometry(QtCore.QRect(10, 10, 91, 81))
        self.Logo2.setStyleSheet("background-color: rgb(34,139,34)")
        self.Logo2.setText("")
        self.Logo2.setPixmap(QtGui.QPixmap("Pic/2.png"))
        self.Logo2.setScaledContents(True)
        self.Logo2.setObjectName("Logo2")
        self.groupBox_side2 = QtWidgets.QGroupBox(self.pre)
        self.groupBox_side2.setGeometry(QtCore.QRect(0, 100, 271, 511))
        self.groupBox_side2.setStyleSheet("background-color: rgb(34,139,34)")
        self.groupBox_side2.setTitle("")
        self.groupBox_side2.setObjectName("groupBox_side2")
        self.BtnResize = QtWidgets.QPushButton(self.groupBox_side2)
        self.BtnResize.setGeometry(QtCore.QRect(30, 110, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(11)
        self.BtnResize.setFont(font)
        self.BtnResize.setStyleSheet("QPushButton {  background-color: rgb(234, 234, 234);   border-radius:12px;}\n"
"QPushButton:pressed {background-color: rgb(189, 213, 234); border-radius:12px; }")
        self.BtnResize.setObjectName("BtnResize")
        self.BtnResize.clicked.connect(self.resizeimg)
        self.BtnContrast = QtWidgets.QPushButton(self.groupBox_side2)
        self.BtnContrast.setGeometry(QtCore.QRect(30, 180, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(11)
        self.BtnContrast.setFont(font)
        self.BtnContrast.setStyleSheet("QPushButton {  background-color: rgb(234, 234, 234);   border-radius:12px;}\n"
"QPushButton:pressed {background-color: rgb(189, 213, 234); border-radius:12px; }")
        self.BtnContrast.setObjectName("BtnContrast")
        self.BtnContrast.clicked.connect(self.contrast)
        self.BtnNoiseR = QtWidgets.QPushButton(self.groupBox_side2)
        self.BtnNoiseR.setGeometry(QtCore.QRect(30, 250, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(11)
        self.BtnNoiseR.setFont(font)
        self.BtnNoiseR.setStyleSheet("QPushButton {  background-color: rgb(234, 234, 234);   border-radius:12px;}\n"
"QPushButton:pressed {background-color: rgb(189, 213, 234); border-radius:12px; }")
        self.BtnNoiseR.setObjectName("BtnNoiseR")
        self.BtnNoiseR.clicked.connect(self.median)
        self.BtnBack1 = QtWidgets.QPushButton(self.groupBox_side2)
        self.BtnBack1.setGeometry(QtCore.QRect(30, 440, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(11)
        self.BtnBack1.setFont(font)
        self.BtnBack1.setStyleSheet("QPushButton {  background-color: rgb(234, 234, 234);   border-radius:12px;}\n"
"QPushButton:pressed {background-color: rgb(189, 213, 234); border-radius:12px; }")
        self.BtnBack1.setObjectName("BtnBack1")
        self.BtnBack1.clicked.connect(self.backtoMain)
        self.BtnClr1 = QtWidgets.QPushButton(self.groupBox_side2)
        self.BtnClr1.setGeometry(QtCore.QRect(30, 320, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(11)
        self.BtnClr1.setFont(font)
        self.BtnClr1.setStyleSheet("QPushButton {  background-color: rgb(234, 234, 234);   border-radius:12px;}\n"
"QPushButton:pressed {background-color: rgb(189, 213, 234); border-radius:12px; }")
        self.BtnClr1.setObjectName("BtnClr1")
        self.BtnClr1.clicked.connect(self.clear1)
        self.image_PP = QtWidgets.QLabel(self.pre)
        self.image_PP.setGeometry(QtCore.QRect(310, 220, 250, 250))
        self.image_PP.setFrameShape(QtWidgets.QFrame.Panel)
        self.image_PP.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.image_PP.setLineWidth(2)
        self.image_PP.setText("")
        self.image_PP.setScaledContents(True)
        self.image_PP.setObjectName("image_PP")
        self.Image_PPout = QtWidgets.QLabel(self.pre)
        self.Image_PPout.setGeometry(QtCore.QRect(590, 220, 250, 250))
        self.Image_PPout.setFrameShape(QtWidgets.QFrame.Panel)
        self.Image_PPout.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Image_PPout.setLineWidth(2)
        self.Image_PPout.setText("")
        self.Image_PPout.setScaledContents(True)
        self.Image_PPout.setObjectName("Image_PPout")
        self.iImage = QtWidgets.QLabel(self.pre)
        self.iImage.setGeometry(QtCore.QRect(310, 190, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.iImage.setFont(font)
        self.iImage.setStyleSheet("color: rgb(251, 248, 255);\n"
"background-color:rgb(34,139,34);")
        self.iImage.setFrameShape(QtWidgets.QFrame.Panel)
        self.iImage.setFrameShadow(QtWidgets.QFrame.Plain)
        self.iImage.setLineWidth(2)
        self.iImage.setAlignment(QtCore.Qt.AlignCenter)
        self.iImage.setObjectName("iImage")
        self.oImage = QtWidgets.QLabel(self.pre)
        self.oImage.setGeometry(QtCore.QRect(590, 189, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.oImage.setFont(font)
        self.oImage.setStyleSheet("color: rgb(251, 248, 255);\n"
"background-color:rgb(34,139,34);")
        self.oImage.setFrameShape(QtWidgets.QFrame.Panel)
        self.oImage.setFrameShadow(QtWidgets.QFrame.Plain)
        self.oImage.setLineWidth(2)
        self.oImage.setAlignment(QtCore.Qt.AlignCenter)
        self.oImage.setObjectName("oImage")
        self.PP_Header = QtWidgets.QLabel(self.pre)
        self.PP_Header.setGeometry(QtCore.QRect(270, 100, 601, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.PP_Header.setFont(font)
        self.PP_Header.setFrameShape(QtWidgets.QFrame.Box)
        self.PP_Header.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.PP_Header.setLineWidth(3)
        self.PP_Header.setAlignment(QtCore.Qt.AlignCenter)
        self.PP_Header.setObjectName("PP_Header")
        self.btnpexe = QtWidgets.QPushButton(self.pre)
        self.btnpexe.setGeometry(QtCore.QRect(310, 480, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(11)
        self.btnpexe.setFont(font)
        self.btnpexe.setStyleSheet("QPushButton {color: rgb(251, 248, 255);\n"
"background-color:rgb(34,139,34);border-radius:10px;}\n"
"QPushButton:pressed { background-color: rgb(189, 213, 234); border-radius:10px; ;}")
        self.btnpexe.setObjectName("btnpexe")
        self.btnpnxt = QtWidgets.QPushButton(self.pre)
        self.btnpnxt.setGeometry(QtCore.QRect(590, 480, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(11)
        self.btnpnxt.setFont(font)
        self.btnpnxt.setStyleSheet("QPushButton {color: rgb(251, 248, 255);\n"
"background-color: rgb(34,139,34);border-radius:10px;}\n"
"QPushButton:pressed { background-color: rgb(189, 213, 234); border-radius:10px; ;}")
        self.btnpnxt.setObjectName("btnpnxt")
        self.btnpnxt.clicked.connect(self.nexttoclass)
        self.stackedWidget.addWidget(self.pre)
        self.classi = QtWidgets.QWidget()
        self.classi.setObjectName("classi")
        self.groupBox_Side3 = QtWidgets.QGroupBox(self.classi)
        self.groupBox_Side3.setGeometry(QtCore.QRect(0, 100, 271, 511))
        self.groupBox_Side3.setStyleSheet("background-color:rgb(34,139,34);")
        self.groupBox_Side3.setTitle("")
        self.groupBox_Side3.setObjectName("groupBox_Side3")
        self.BtnPred = QtWidgets.QPushButton(self.groupBox_Side3)
        self.BtnPred.setGeometry(QtCore.QRect(30, 170, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.BtnPred.setFont(font)
        self.BtnPred.setStyleSheet("QPushButton {  background-color: rgb(234, 234, 234);   border-radius:12px;}\n"
"QPushButton:pressed {background-color: rgb(189, 213, 234); border-radius:12px; }")
        self.BtnPred.setChecked(False)
        self.BtnPred.setObjectName("BtnPred")
        self.BtnPred.clicked.connect(self.predict)
        self.BtnBack2 = QtWidgets.QPushButton(self.groupBox_Side3)
        self.BtnBack2.setGeometry(QtCore.QRect(30, 440, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.BtnBack2.setFont(font)
        self.BtnBack2.setStyleSheet("QPushButton {  background-color: rgb(234, 234, 234);   border-radius:12px;}\n"
"QPushButton:pressed {background-color: rgb(189, 213, 234); border-radius:12px; }")
        self.BtnBack2.setObjectName("BtnBack2")
        self.BtnBack2.clicked.connect(self.backtoMain)
        self.BtnClr2 = QtWidgets.QPushButton(self.groupBox_Side3)
        self.BtnClr2.setGeometry(QtCore.QRect(30, 250, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.BtnClr2.setFont(font)
        self.BtnClr2.setStyleSheet("QPushButton {  background-color: rgb(234, 234, 234);   border-radius:12px;}\n"
"QPushButton:pressed {background-color: rgb(189, 213, 234); border-radius:12px; }")
        self.BtnClr2.setObjectName("BtnClr2")
        self.BtnClr2.clicked.connect(self.clear2)
        self.ImageView2 = QtWidgets.QLabel(self.classi)
        self.ImageView2.setGeometry(QtCore.QRect(310, 220, 250, 250))
        self.ImageView2.setFrameShape(QtWidgets.QFrame.Box)
        self.ImageView2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.ImageView2.setLineWidth(3)
        self.ImageView2.setText("")
        self.ImageView2.setScaledContents(True)
        self.ImageView2.setObjectName("ImageView2")
        self.Image2 = QtWidgets.QLabel(self.classi)
        self.Image2.setGeometry(QtCore.QRect(310, 189, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Image2.setFont(font)
        self.Image2.setStyleSheet("color: rgb(251, 248, 255);;\n"
"background-color: rgb(34,139,34)")
        self.Image2.setLineWidth(0)
        self.Image2.setAlignment(QtCore.Qt.AlignCenter)
        self.Image2.setObjectName("Image2")
        self.Classifier_header = QtWidgets.QLabel(self.classi)
        self.Classifier_header.setGeometry(QtCore.QRect(270, 100, 601, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Classifier_header.setFont(font)
        self.Classifier_header.setFrameShape(QtWidgets.QFrame.Box)
        self.Classifier_header.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Classifier_header.setLineWidth(3)
        self.Classifier_header.setAlignment(QtCore.Qt.AlignCenter)
        self.Classifier_header.setObjectName("Classifier_header")
        self.Result_box = QtWidgets.QGroupBox(self.classi)
        self.Result_box.setGeometry(QtCore.QRect(580, 230, 261, 201))
        font = QtGui.QFont()
        font.setFamily("Microsoft Himalaya")
        font.setPointSize(16)
        self.Result_box.setFont(font)
        self.Result_box.setObjectName("Result_box")
        self.prediction = QtWidgets.QLabel(self.Result_box)
        self.prediction.setGeometry(QtCore.QRect(10, 80, 241, 51))
        self.prediction.setFrameShape(QtWidgets.QFrame.Box)
        self.prediction.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.prediction.setLineWidth(2)
        self.prediction.setScaledContents(True)
        self.prediction.setText("")
        self.prediction.setObjectName("prediction")
        self.label_35 = QtWidgets.QLabel(self.Result_box)
        self.label_35.setGeometry(QtCore.QRect(10, 30, 241, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_35.setFont(font)
        self.label_35.setAlignment(QtCore.Qt.AlignCenter)
        self.label_35.setObjectName("label_35")
        self.Header3 = QtWidgets.QLabel(self.classi)
        self.Header3.setGeometry(QtCore.QRect(0, 0, 871, 101))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Header3.setFont(font)
        self.Header3.setStyleSheet("color: rgb(251, 248, 255);\n"
"background-color: rgb(34,139,34)")
        self.Header3.setFrameShape(QtWidgets.QFrame.Panel)
        self.Header3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Header3.setLineWidth(6)
        self.Header3.setAlignment(QtCore.Qt.AlignCenter)
        self.Header3.setObjectName("Header3")
        self.Logo2_3 = QtWidgets.QLabel(self.classi)
        self.Logo2_3.setGeometry(QtCore.QRect(10, 10, 91, 81))
        self.Logo2_3.setStyleSheet("background-color: rgb(34,139,34)")
        self.Logo2_3.setText("")
        self.Logo2_3.setPixmap(QtGui.QPixmap("Pic/2.png"))
        self.Logo2_3.setScaledContents(True)
        self.Logo2_3.setObjectName("Logo2_3")
        self.stackedWidget.addWidget(self.classi)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.Header3_2 = QtWidgets.QLabel(self.page)
        self.Header3_2.setGeometry(QtCore.QRect(0, 0, 871, 101))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Header3_2.setFont(font)
        self.Header3_2.setStyleSheet("color: rgb(251, 248, 255);\n"
"background-color: rgb(34,139,34)")
        self.Header3_2.setFrameShape(QtWidgets.QFrame.Panel)
        self.Header3_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Header3_2.setLineWidth(6)
        self.Header3_2.setAlignment(QtCore.Qt.AlignCenter)
        self.Header3_2.setObjectName("Header3_2")
        self.label = QtWidgets.QLabel(self.page)
        self.label.setGeometry(QtCore.QRect(10, 110, 851, 481))
        self.label.setStyleSheet("background-color: rgb(34,139,34)")
        self.label.setText("")
        self.label.setObjectName("label")
        self.BtnBack2_2 = QtWidgets.QPushButton(self.page)
        self.BtnBack2_2.setGeometry(QtCore.QRect(100, 530, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.BtnBack2_2.setFont(font)
        self.BtnBack2_2.setStyleSheet("QPushButton {  background-color: rgb(234, 234, 234);   border-radius:12px;}\n"
"QPushButton:pressed {background-color: rgb(189, 213, 234); border-radius:12px; }")
        self.BtnBack2_2.setObjectName("BtnBack2_2")
        self.BtnBack2_2.clicked.connect(self.backtoMain)
        self.BtnNext2 = QtWidgets.QPushButton(self.page)
        self.BtnNext2.setGeometry(QtCore.QRect(540, 530, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.BtnNext2.setFont(font)
        self.BtnNext2.setStyleSheet("QPushButton {  background-color: rgb(234, 234, 234);   border-radius:12px;}\n"
"QPushButton:pressed {background-color: rgb(189, 213, 234); border-radius:12px; }")
        self.BtnNext2.setObjectName("BtnNext2")
        self.BtnNext2.clicked.connect(self.Tutorial2)
        self.TOT_Image = QtWidgets.QLabel(self.page)
        self.TOT_Image.setGeometry(QtCore.QRect(20, 120, 831, 401))
        self.TOT_Image.setText("")
        self.TOT_Image.setPixmap(QtGui.QPixmap("Pic/TOT1.jpg"))
        self.TOT_Image.setScaledContents(True)
        self.TOT_Image.setObjectName("TOT_Image")
        self.Logo1_3 = QtWidgets.QLabel(self.page)
        self.Logo1_3.setGeometry(QtCore.QRect(10, 10, 91, 81))
        self.Logo1_3.setStyleSheet("background-color: rgb(34,139,34)")
        self.Logo1_3.setText("")
        self.Logo1_3.setPixmap(QtGui.QPixmap("Pic/2.png"))
        self.Logo1_3.setScaledContents(True)
        self.Logo1_3.setObjectName("Logo1_3")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.Header3_3 = QtWidgets.QLabel(self.page_2)
        self.Header3_3.setGeometry(QtCore.QRect(0, 0, 871, 101))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Header3_3.setFont(font)
        self.Header3_3.setStyleSheet("color: rgb(251, 248, 255);\n"
"background-color: rgb(34,139,34)")
        self.Header3_3.setFrameShape(QtWidgets.QFrame.Panel)
        self.Header3_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Header3_3.setLineWidth(6)
        self.Header3_3.setAlignment(QtCore.Qt.AlignCenter)
        self.Header3_3.setObjectName("Header3_3")
        self.label_2 = QtWidgets.QLabel(self.page_2)
        self.label_2.setGeometry(QtCore.QRect(10, 110, 851, 481))
        self.label_2.setStyleSheet("background-color: rgb(34,139,34)")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.TOT_Image_2 = QtWidgets.QLabel(self.page_2)
        self.TOT_Image_2.setGeometry(QtCore.QRect(20, 120, 831, 401))
        self.TOT_Image_2.setText("")
        self.TOT_Image_2.setPixmap(QtGui.QPixmap("Pic/TOT2.jpg"))
        self.TOT_Image_2.setScaledContents(True)
        self.TOT_Image_2.setObjectName("TOT_Image_2")
        self.BtnBack2_4 = QtWidgets.QPushButton(self.page_2)
        self.BtnBack2_4.setGeometry(QtCore.QRect(100, 530, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.BtnBack2_4.setFont(font)
        self.BtnBack2_4.setStyleSheet("QPushButton {  background-color: rgb(234, 234, 234);   border-radius:12px;}\n"
"QPushButton:pressed {background-color: rgb(189, 213, 234); border-radius:12px; }")
        self.BtnBack2_4.setObjectName("BtnBack2_4")
        self.BtnBack2_4.clicked.connect(self.backtoMain)
        self.BtnNext3 = QtWidgets.QPushButton(self.page_2)
        self.BtnNext3.setGeometry(QtCore.QRect(540, 530, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.BtnNext3.setFont(font)
        self.BtnNext3.setStyleSheet("QPushButton {  background-color: rgb(234, 234, 234);   border-radius:12px;}\n"
"QPushButton:pressed {background-color: rgb(189, 213, 234); border-radius:12px; }")
        self.BtnNext3.setObjectName("BtnNext3")
        self.BtnNext3.clicked.connect(self.Tutorial3)
        self.BtnBack2_6 = QtWidgets.QPushButton(self.page_2)
        self.BtnBack2_6.setGeometry(QtCore.QRect(320, 530, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.BtnBack2_6.setFont(font)
        self.BtnBack2_6.setStyleSheet("QPushButton {  background-color: rgb(234, 234, 234);   border-radius:12px;}\n"
"QPushButton:pressed {background-color: rgb(189, 213, 234); border-radius:12px; }")
        self.BtnBack2_6.setObjectName("BtnBack2_6")
        self.BtnBack2_6.clicked.connect(self.Tutorial1)
        self.Logo1_4 = QtWidgets.QLabel(self.page_2)
        self.Logo1_4.setGeometry(QtCore.QRect(10, 10, 91, 81))
        self.Logo1_4.setStyleSheet("background-color: rgb(34,139,34)")
        self.Logo1_4.setText("")
        self.Logo1_4.setPixmap(QtGui.QPixmap("Pic/2.png"))
        self.Logo1_4.setScaledContents(True)
        self.Logo1_4.setObjectName("Logo1_4")
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.stackedWidget_2 = QtWidgets.QStackedWidget(self.page_3)
        self.stackedWidget_2.setGeometry(QtCore.QRect(0, 0, 871, 601))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.stackedWidget_2.setFont(font)
        self.stackedWidget_2.setStyleSheet("background-color: rgb(234, 234, 234); ")
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.Mian_2 = QtWidgets.QWidget()
        self.Mian_2.setObjectName("Mian_2")
        self.groupBox_side1_2 = QtWidgets.QGroupBox(self.Mian_2)
        self.groupBox_side1_2.setGeometry(QtCore.QRect(-10, 100, 271, 511))
        self.groupBox_side1_2.setStyleSheet("background-color:rgb(34,139,34)")
        self.groupBox_side1_2.setTitle("")
        self.groupBox_side1_2.setObjectName("groupBox_side1_2")
        self.BtnPP_2 = QtWidgets.QPushButton(self.groupBox_side1_2)
        self.BtnPP_2.setGeometry(QtCore.QRect(30, 190, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(11)
        self.BtnPP_2.setFont(font)
        self.BtnPP_2.setStyleSheet("QPushButton {  background-color: rgb(234, 234, 234);   border-radius:12px;}\n"
"QPushButton:pressed {background-color: rgb(189, 213, 234); border-radius:12px; }")
        self.BtnPP_2.setObjectName("BtnPP_2")
        self.BtnClass_2 = QtWidgets.QPushButton(self.groupBox_side1_2)
        self.BtnClass_2.setGeometry(QtCore.QRect(30, 270, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(11)
        self.BtnClass_2.setFont(font)
        self.BtnClass_2.setStyleSheet("QPushButton {  background-color: rgb(234, 234, 234);   border-radius:12px;}\n"
"QPushButton:pressed {background-color: rgb(189, 213, 234); border-radius:12px; }")
        self.BtnClass_2.setObjectName("BtnClass_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_side1_2)
        self.pushButton_2.setGeometry(QtCore.QRect(230, 470, 31, 23))
        self.pushButton_2.setStyleSheet("QPushButton {  background-color: rgb(234, 234, 234);   border-radius:5px;}\n"
"QPushButton:pressed {background-color: rgb(189, 213, 234); border-radius:5px; }")
        self.pushButton_2.setObjectName("pushButton_2")
        self.MainWindowH_2 = QtWidgets.QLabel(self.Mian_2)
        self.MainWindowH_2.setGeometry(QtCore.QRect(260, 100, 611, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.MainWindowH_2.setFont(font)
        self.MainWindowH_2.setFrameShape(QtWidgets.QFrame.Box)
        self.MainWindowH_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.MainWindowH_2.setLineWidth(3)
        self.MainWindowH_2.setAlignment(QtCore.Qt.AlignCenter)
        self.MainWindowH_2.setObjectName("MainWindowH_2")
        self.Header1_2 = QtWidgets.QLabel(self.Mian_2)
        self.Header1_2.setGeometry(QtCore.QRect(0, 0, 871, 101))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Header1_2.setFont(font)
        self.Header1_2.setStyleSheet("color: rgb(251, 248, 255);\n"
"background-color: rgb(34,139,34)")
        self.Header1_2.setFrameShape(QtWidgets.QFrame.Panel)
        self.Header1_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Header1_2.setLineWidth(6)
        self.Header1_2.setAlignment(QtCore.Qt.AlignCenter)
        self.Header1_2.setObjectName("Header1_2")
        self.Logo1_2 = QtWidgets.QLabel(self.Mian_2)
        self.Logo1_2.setGeometry(QtCore.QRect(10, 10, 91, 81))
        self.Logo1_2.setStyleSheet("background-color: rgb(34,139,34)")
        self.Logo1_2.setText("")
        self.Logo1_2.setPixmap(QtGui.QPixmap("Pic/2.png"))
        self.Logo1_2.setScaledContents(True)
        self.Logo1_2.setObjectName("Logo1_2")
        self.ImageView_2 = QtWidgets.QLabel(self.Mian_2)
        self.ImageView_2.setGeometry(QtCore.QRect(580, 250, 250, 250))
        self.ImageView_2.setFrameShape(QtWidgets.QFrame.Panel)
        self.ImageView_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.ImageView_2.setLineWidth(2)
        self.ImageView_2.setText("")
        self.ImageView_2.setObjectName("ImageView_2")
        self.label_4 = QtWidgets.QLabel(self.Mian_2)
        self.label_4.setGeometry(QtCore.QRect(410, 260, 121, 111))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("Pic/8.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.Btn_Upload_2 = QtWidgets.QPushButton(self.Mian_2)
        self.Btn_Upload_2.setGeometry(QtCore.QRect(400, 390, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(8)
        self.Btn_Upload_2.setFont(font)
        self.Btn_Upload_2.setStyleSheet("QPushButton {color: rgb(251, 248, 255);\n"
"background-color: rgb(34,139,34);border-radius:10px;}\n"
"QPushButton:pressed { background-color: rgb(189, 213, 234); border-radius:10px; ;}")
        self.Btn_Upload_2.setObjectName("Btn_Upload_2")
        self.Btn_remove_2 = QtWidgets.QPushButton(self.Mian_2)
        self.Btn_remove_2.setGeometry(QtCore.QRect(400, 450, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(8)
        self.Btn_remove_2.setFont(font)
        self.Btn_remove_2.setStyleSheet("QPushButton {color: rgb(251, 248, 255);\n"
"background-color: rgb(34,139,34);border-radius:10px;}\n"
"QPushButton:pressed { background-color: rgb(189, 213, 234); border-radius:10px; ;}")
        self.Btn_remove_2.setObjectName("Btn_remove_2")
        self.Image_2 = QtWidgets.QLabel(self.Mian_2)
        self.Image_2.setGeometry(QtCore.QRect(580, 220, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.Image_2.setFont(font)
        self.Image_2.setStyleSheet("color: rgb(251, 248, 255);\n"
"background-color: rgb(34,139,34)")
        self.Image_2.setFrameShape(QtWidgets.QFrame.Panel)
        self.Image_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.Image_2.setLineWidth(2)
        self.Image_2.setAlignment(QtCore.Qt.AlignCenter)
        self.Image_2.setObjectName("Image_2")
        self.stackedWidget_2.addWidget(self.Mian_2)
        self.pre_2 = QtWidgets.QWidget()
        self.pre_2.setObjectName("pre_2")
        self.Header2_2 = QtWidgets.QLabel(self.pre_2)
        self.Header2_2.setGeometry(QtCore.QRect(0, 0, 871, 101))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Header2_2.setFont(font)
        self.Header2_2.setStyleSheet("color: rgb(251, 248, 255);\n"
"background-color: rgb(34,139,34)")
        self.Header2_2.setFrameShape(QtWidgets.QFrame.Panel)
        self.Header2_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Header2_2.setLineWidth(6)
        self.Header2_2.setAlignment(QtCore.Qt.AlignCenter)
        self.Header2_2.setObjectName("Header2_2")
        self.Logo2_2 = QtWidgets.QLabel(self.pre_2)
        self.Logo2_2.setGeometry(QtCore.QRect(10, 10, 91, 81))
        self.Logo2_2.setStyleSheet("background-color: rgb(34,139,34)")
        self.Logo2_2.setText("")
        self.Logo2_2.setPixmap(QtGui.QPixmap("Pic/2.png"))
        self.Logo2_2.setScaledContents(True)
        self.Logo2_2.setObjectName("Logo2_2")
        self.groupBox_side2_2 = QtWidgets.QGroupBox(self.pre_2)
        self.groupBox_side2_2.setGeometry(QtCore.QRect(0, 100, 271, 511))
        self.groupBox_side2_2.setStyleSheet("background-color: rgb(34,139,34)")
        self.groupBox_side2_2.setTitle("")
        self.groupBox_side2_2.setObjectName("groupBox_side2_2")
        self.BtnResize_2 = QtWidgets.QPushButton(self.groupBox_side2_2)
        self.BtnResize_2.setGeometry(QtCore.QRect(30, 110, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(11)
        self.BtnResize_2.setFont(font)
        self.BtnResize_2.setStyleSheet("QPushButton {  background-color: rgb(234, 234, 234);   border-radius:12px;}\n"
"QPushButton:pressed {background-color: rgb(189, 213, 234); border-radius:12px; }")
        self.BtnResize_2.setObjectName("BtnResize_2")
        self.BtnContrast_2 = QtWidgets.QPushButton(self.groupBox_side2_2)
        self.BtnContrast_2.setGeometry(QtCore.QRect(30, 180, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(11)
        self.BtnContrast_2.setFont(font)
        self.BtnContrast_2.setStyleSheet("QPushButton {  background-color: rgb(234, 234, 234);   border-radius:12px;}\n"
"QPushButton:pressed {background-color: rgb(189, 213, 234); border-radius:12px; }")
        self.BtnContrast_2.setObjectName("BtnContrast_2")
        self.BtnNoiseR_2 = QtWidgets.QPushButton(self.groupBox_side2_2)
        self.BtnNoiseR_2.setGeometry(QtCore.QRect(30, 250, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(11)
        self.BtnNoiseR_2.setFont(font)
        self.BtnNoiseR_2.setStyleSheet("QPushButton {  background-color: rgb(234, 234, 234);   border-radius:12px;}\n"
"QPushButton:pressed {background-color: rgb(189, 213, 234); border-radius:12px; }")
        self.BtnNoiseR_2.setObjectName("BtnNoiseR_2")
        self.BtnBack1_2 = QtWidgets.QPushButton(self.groupBox_side2_2)
        self.BtnBack1_2.setGeometry(QtCore.QRect(30, 440, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(11)
        self.BtnBack1_2.setFont(font)
        self.BtnBack1_2.setStyleSheet("QPushButton {  background-color: rgb(234, 234, 234);   border-radius:12px;}\n"
"QPushButton:pressed {background-color: rgb(189, 213, 234); border-radius:12px; }")
        self.BtnBack1_2.setObjectName("BtnBack1_2")
        self.BtnClr1_2 = QtWidgets.QPushButton(self.groupBox_side2_2)
        self.BtnClr1_2.setGeometry(QtCore.QRect(30, 320, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(11)
        self.BtnClr1_2.setFont(font)
        self.BtnClr1_2.setStyleSheet("QPushButton {  background-color: rgb(234, 234, 234);   border-radius:12px;}\n"
"QPushButton:pressed {background-color: rgb(189, 213, 234); border-radius:12px; }")
        self.BtnClr1_2.setObjectName("BtnClr1_2")
        self.image_PP_2 = QtWidgets.QLabel(self.pre_2)
        self.image_PP_2.setGeometry(QtCore.QRect(310, 220, 250, 250))
        self.image_PP_2.setFrameShape(QtWidgets.QFrame.Panel)
        self.image_PP_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.image_PP_2.setLineWidth(2)
        self.image_PP_2.setText("")
        self.image_PP_2.setObjectName("image_PP_2")
        self.Image_PPout_2 = QtWidgets.QLabel(self.pre_2)
        self.Image_PPout_2.setGeometry(QtCore.QRect(590, 220, 250, 250))
        self.Image_PPout_2.setFrameShape(QtWidgets.QFrame.Panel)
        self.Image_PPout_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Image_PPout_2.setLineWidth(2)
        self.Image_PPout_2.setText("")
        self.Image_PPout_2.setObjectName("Image_PPout_2")
        self.iImage_2 = QtWidgets.QLabel(self.pre_2)
        self.iImage_2.setGeometry(QtCore.QRect(310, 190, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.iImage_2.setFont(font)
        self.iImage_2.setStyleSheet("color: rgb(251, 248, 255);\n"
"background-color:rgb(34,139,34);")
        self.iImage_2.setFrameShape(QtWidgets.QFrame.Panel)
        self.iImage_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.iImage_2.setLineWidth(2)
        self.iImage_2.setAlignment(QtCore.Qt.AlignCenter)
        self.iImage_2.setObjectName("iImage_2")
        self.oImage_2 = QtWidgets.QLabel(self.pre_2)
        self.oImage_2.setGeometry(QtCore.QRect(590, 189, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.oImage_2.setFont(font)
        self.oImage_2.setStyleSheet("color: rgb(251, 248, 255);\n"
"background-color:rgb(34,139,34);")
        self.oImage_2.setFrameShape(QtWidgets.QFrame.Panel)
        self.oImage_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.oImage_2.setLineWidth(2)
        self.oImage_2.setAlignment(QtCore.Qt.AlignCenter)
        self.oImage_2.setObjectName("oImage_2")
        self.PP_Header_2 = QtWidgets.QLabel(self.pre_2)
        self.PP_Header_2.setGeometry(QtCore.QRect(270, 100, 601, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.PP_Header_2.setFont(font)
        self.PP_Header_2.setFrameShape(QtWidgets.QFrame.Box)
        self.PP_Header_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.PP_Header_2.setLineWidth(3)
        self.PP_Header_2.setAlignment(QtCore.Qt.AlignCenter)
        self.PP_Header_2.setObjectName("PP_Header_2")
        self.btnpexe_2 = QtWidgets.QPushButton(self.pre_2)
        self.btnpexe_2.setGeometry(QtCore.QRect(310, 480, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(11)
        self.btnpexe_2.setFont(font)
        self.btnpexe_2.setStyleSheet("QPushButton {color: rgb(251, 248, 255);\n"
"background-color:rgb(34,139,34);border-radius:10px;}\n"
"QPushButton:pressed { background-color: rgb(189, 213, 234); border-radius:10px; ;}")
        self.btnpexe_2.setObjectName("btnpexe_2")
        self.btnpnxt_2 = QtWidgets.QPushButton(self.pre_2)
        self.btnpnxt_2.setGeometry(QtCore.QRect(590, 480, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(11)
        self.btnpnxt_2.setFont(font)
        self.btnpnxt_2.setStyleSheet("QPushButton {color: rgb(251, 248, 255);\n"
"background-color: rgb(34,139,34);border-radius:10px;}\n"
"QPushButton:pressed { background-color: rgb(189, 213, 234); border-radius:10px; ;}")
        self.btnpnxt_2.setObjectName("btnpnxt_2")
        self.stackedWidget_2.addWidget(self.pre_2)
        self.classi_2 = QtWidgets.QWidget()
        self.classi_2.setObjectName("classi_2")
        self.groupBox_Side3_2 = QtWidgets.QGroupBox(self.classi_2)
        self.groupBox_Side3_2.setGeometry(QtCore.QRect(0, 100, 271, 511))
        self.groupBox_Side3_2.setStyleSheet("background-color:rgb(34,139,34);")
        self.groupBox_Side3_2.setTitle("")
        self.groupBox_Side3_2.setObjectName("groupBox_Side3_2")
        self.BtnPred_2 = QtWidgets.QPushButton(self.groupBox_Side3_2)
        self.BtnPred_2.setGeometry(QtCore.QRect(30, 170, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.BtnPred_2.setFont(font)
        self.BtnPred_2.setStyleSheet("QPushButton {  background-color: rgb(234, 234, 234);   border-radius:12px;}\n"
"QPushButton:pressed {background-color: rgb(189, 213, 234); border-radius:12px; }")
        self.BtnPred_2.setChecked(False)
        self.BtnPred_2.setObjectName("BtnPred_2")
        self.BtnBack2_7 = QtWidgets.QPushButton(self.groupBox_Side3_2)
        self.BtnBack2_7.setGeometry(QtCore.QRect(30, 440, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.BtnBack2_7.setFont(font)
        self.BtnBack2_7.setStyleSheet("QPushButton {  background-color: rgb(234, 234, 234);   border-radius:12px;}\n"
"QPushButton:pressed {background-color: rgb(189, 213, 234); border-radius:12px; }")
        self.BtnBack2_7.setObjectName("BtnBack2_7")
        self.BtnClr2_2 = QtWidgets.QPushButton(self.groupBox_Side3_2)
        self.BtnClr2_2.setGeometry(QtCore.QRect(30, 250, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.BtnClr2_2.setFont(font)
        self.BtnClr2_2.setStyleSheet("QPushButton {  background-color: rgb(234, 234, 234);   border-radius:12px;}\n"
"QPushButton:pressed {background-color: rgb(189, 213, 234); border-radius:12px; }")
        self.BtnClr2_2.setObjectName("BtnClr2_2")
        self.ImageView2_2 = QtWidgets.QLabel(self.classi_2)
        self.ImageView2_2.setGeometry(QtCore.QRect(310, 220, 250, 250))
        self.ImageView2_2.setFrameShape(QtWidgets.QFrame.Box)
        self.ImageView2_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.ImageView2_2.setLineWidth(3)
        self.ImageView2_2.setText("")
        self.ImageView2_2.setObjectName("ImageView2_2")
        self.Image2_2 = QtWidgets.QLabel(self.classi_2)
        self.Image2_2.setGeometry(QtCore.QRect(310, 189, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Image2_2.setFont(font)
        self.Image2_2.setStyleSheet("color: rgb(251, 248, 255);;\n"
"background-color: rgb(34,139,34)")
        self.Image2_2.setLineWidth(0)
        self.Image2_2.setAlignment(QtCore.Qt.AlignCenter)
        self.Image2_2.setObjectName("Image2_2")
        self.Classifier_header_2 = QtWidgets.QLabel(self.classi_2)
        self.Classifier_header_2.setGeometry(QtCore.QRect(270, 100, 601, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Classifier_header_2.setFont(font)
        self.Classifier_header_2.setFrameShape(QtWidgets.QFrame.Box)
        self.Classifier_header_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Classifier_header_2.setLineWidth(3)
        self.Classifier_header_2.setAlignment(QtCore.Qt.AlignCenter)
        self.Classifier_header_2.setObjectName("Classifier_header_2")
        self.Result_box_2 = QtWidgets.QGroupBox(self.classi_2)
        self.Result_box_2.setGeometry(QtCore.QRect(580, 230, 261, 201))
        font = QtGui.QFont()
        font.setFamily("Microsoft Himalaya")
        font.setPointSize(16)
        self.Result_box_2.setFont(font)
        self.Result_box_2.setObjectName("Result_box_2")
        self.prediction_2 = QtWidgets.QLabel(self.Result_box_2)
        self.prediction_2.setGeometry(QtCore.QRect(10, 80, 241, 51))
        self.prediction_2.setFrameShape(QtWidgets.QFrame.Box)
        self.prediction_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.prediction_2.setLineWidth(2)
        self.prediction_2.setText("")
        self.prediction_2.setObjectName("prediction_2")
        self.label_36 = QtWidgets.QLabel(self.Result_box_2)
        self.label_36.setGeometry(QtCore.QRect(10, 30, 241, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_36.setFont(font)
        self.label_36.setAlignment(QtCore.Qt.AlignCenter)
        self.label_36.setObjectName("label_36")
        self.Header3_4 = QtWidgets.QLabel(self.classi_2)
        self.Header3_4.setGeometry(QtCore.QRect(0, 0, 871, 101))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Header3_4.setFont(font)
        self.Header3_4.setStyleSheet("color: rgb(251, 248, 255);\n"
"background-color: rgb(34,139,34)")
        self.Header3_4.setFrameShape(QtWidgets.QFrame.Panel)
        self.Header3_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Header3_4.setLineWidth(6)
        self.Header3_4.setAlignment(QtCore.Qt.AlignCenter)
        self.Header3_4.setObjectName("Header3_4")
        self.stackedWidget_2.addWidget(self.classi_2)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.Header3_5 = QtWidgets.QLabel(self.page_4)
        self.Header3_5.setGeometry(QtCore.QRect(0, 0, 871, 101))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Header3_5.setFont(font)
        self.Header3_5.setStyleSheet("color: rgb(251, 248, 255);\n"
"background-color: rgb(34,139,34)")
        self.Header3_5.setFrameShape(QtWidgets.QFrame.Panel)
        self.Header3_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Header3_5.setLineWidth(6)
        self.Header3_5.setAlignment(QtCore.Qt.AlignCenter)
        self.Header3_5.setObjectName("Header3_5")
        self.label_5 = QtWidgets.QLabel(self.page_4)
        self.label_5.setGeometry(QtCore.QRect(10, 110, 851, 481))
        self.label_5.setStyleSheet("background-color: rgb(34,139,34)")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.BtnBack2_8 = QtWidgets.QPushButton(self.page_4)
        self.BtnBack2_8.setGeometry(QtCore.QRect(100, 530, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.BtnBack2_8.setFont(font)
        self.BtnBack2_8.setStyleSheet("QPushButton {  background-color: rgb(234, 234, 234);   border-radius:12px;}\n"
"QPushButton:pressed {background-color: rgb(189, 213, 234); border-radius:12px; }")
        self.BtnBack2_8.setObjectName("BtnBack2_8")
        self.BtnBack2_9 = QtWidgets.QPushButton(self.page_4)
        self.BtnBack2_9.setGeometry(QtCore.QRect(540, 530, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.BtnBack2_9.setFont(font)
        self.BtnBack2_9.setStyleSheet("QPushButton {  background-color: rgb(234, 234, 234);   border-radius:12px;}\n"
"QPushButton:pressed {background-color: rgb(189, 213, 234); border-radius:12px; }")
        self.BtnBack2_9.setObjectName("BtnBack2_9")
        self.TOT_Image_3 = QtWidgets.QLabel(self.page_4)
        self.TOT_Image_3.setGeometry(QtCore.QRect(20, 120, 831, 401))
        self.TOT_Image_3.setText("")
        self.TOT_Image_3.setPixmap(QtGui.QPixmap("Pic/TOT3.jpg"))
        self.TOT_Image_3.setScaledContents(True)
        self.TOT_Image_3.setObjectName("TOT_Image_3")
        self.stackedWidget_2.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.Header3_6 = QtWidgets.QLabel(self.page_5)
        self.Header3_6.setGeometry(QtCore.QRect(0, 0, 871, 101))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Header3_6.setFont(font)
        self.Header3_6.setStyleSheet("color: rgb(251, 248, 255);\n"
"background-color: rgb(34,139,34)")
        self.Header3_6.setFrameShape(QtWidgets.QFrame.Panel)
        self.Header3_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Header3_6.setLineWidth(6)
        self.Header3_6.setAlignment(QtCore.Qt.AlignCenter)
        self.Header3_6.setObjectName("Header3_6")
        self.label_6 = QtWidgets.QLabel(self.page_5)
        self.label_6.setGeometry(QtCore.QRect(10, 110, 851, 481))
        self.label_6.setStyleSheet("background-color: rgb(34,139,34)")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.TOT_Image_4 = QtWidgets.QLabel(self.page_5)
        self.TOT_Image_4.setGeometry(QtCore.QRect(20, 120, 831, 401))
        self.TOT_Image_4.setText("")
        self.TOT_Image_4.setPixmap(QtGui.QPixmap("Pic/TOT3.jpg"))
        self.TOT_Image_4.setScaledContents(True)
        self.TOT_Image_4.setObjectName("TOT_Image_4")
        self.BtnBack2_10 = QtWidgets.QPushButton(self.page_5)
        self.BtnBack2_10.setGeometry(QtCore.QRect(100, 530, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.BtnBack2_10.setFont(font)
        self.BtnBack2_10.setStyleSheet("QPushButton {  background-color: rgb(234, 234, 234);   border-radius:12px;}\n"
"QPushButton:pressed {background-color: rgb(189, 213, 234); border-radius:12px; }")
        self.BtnBack2_10.setObjectName("BtnBack2_10")
        self.BtnBack2_10.clicked.connect(self.backtoMain)
        self.BtnBack2_11 = QtWidgets.QPushButton(self.page_5)
        self.BtnBack2_11.setGeometry(QtCore.QRect(540, 530, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.BtnBack2_11.setFont(font)
        self.BtnBack2_11.setStyleSheet("QPushButton {  background-color: rgb(234, 234, 234);   border-radius:12px;}\n"
"QPushButton:pressed {background-color: rgb(189, 213, 234); border-radius:12px; }")
        self.BtnBack2_11.setObjectName("BtnBack2_11")
        self.BtnBack2_11.clicked.connect(self.Tutorial2)
        self.Logo1_5 = QtWidgets.QLabel(self.page_5)
        self.Logo1_5.setGeometry(QtCore.QRect(10, 10, 91, 81))
        self.Logo1_5.setStyleSheet("background-color: rgb(34,139,34)")
        self.Logo1_5.setText("")
        self.Logo1_5.setPixmap(QtGui.QPixmap("Pic/2.png"))
        self.Logo1_5.setScaledContents(True)
        self.Logo1_5.setObjectName("Logo1_5")
        self.stackedWidget_2.addWidget(self.page_5)
        self.stackedWidget.addWidget(self.page_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.stackedWidget_2.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Automated Fruit Freshness Recognition System"))
        self.BtnPP.setText(_translate("MainWindow", "Pre-Processing"))
        self.BtnClass.setText(_translate("MainWindow", "Classifier"))
        self.pushButton.setText(_translate("MainWindow", "Help!"))
        self.label_7.setText(_translate("MainWindow", "Main Window"))
        self.Header1.setText(_translate("MainWindow", "Automated Fruit Freshness Recognition System"))
        self.Btn_Upload.setText(_translate("MainWindow", "Upload Image"))
        self.Btn_remove.setText(_translate("MainWindow", "Remove Image"))
        self.Image.setText(_translate("MainWindow", "Input Image"))
        self.Header2.setText(_translate("MainWindow", "Automated Fruit Freshness Recognition System"))
        self.BtnResize.setText(_translate("MainWindow", "Image Resizing"))
        self.BtnContrast.setText(_translate("MainWindow", "Contrast Enhancement"))
        self.BtnNoiseR.setText(_translate("MainWindow", "Noise Removal"))
        self.BtnBack1.setText(_translate("MainWindow", "Back"))
        self.BtnClr1.setText(_translate("MainWindow", "Clear All"))
        self.iImage.setText(_translate("MainWindow", "Input Image"))
        self.oImage.setText(_translate("MainWindow", "Output Image"))
        self.PP_Header.setText(_translate("MainWindow", "Pre-Processing"))
        self.btnpexe.setText(_translate("MainWindow", "Existing Image"))
        self.btnpnxt.setText(_translate("MainWindow", "Next"))
        self.BtnPred.setText(_translate("MainWindow", "Prediction"))
        self.BtnBack2.setText(_translate("MainWindow", "Back"))
        self.BtnClr2.setText(_translate("MainWindow", "Clear All"))
        self.Image2.setText(_translate("MainWindow", "Input Image"))
        self.Classifier_header.setText(_translate("MainWindow", "Classifier"))
        self.Result_box.setTitle(_translate("MainWindow", "Results"))
        self.label_35.setText(_translate("MainWindow", "Prediction"))
        self.Header3.setText(_translate("MainWindow", "Automated Fruit Freshness Recognition System"))
        self.Header3_2.setText(_translate("MainWindow", "Automated Fruit Freshness Recognition System"))
        self.BtnBack2_2.setText(_translate("MainWindow", "Back to Main Window"))
        self.BtnNext2.setText(_translate("MainWindow", "Next"))
        self.Header3_3.setText(_translate("MainWindow", "Automated Fruit Freshness Recognition System"))
        self.BtnBack2_4.setText(_translate("MainWindow", "Back to Main Window"))
        self.BtnNext3.setText(_translate("MainWindow", "Next"))
        self.BtnBack2_6.setText(_translate("MainWindow", "Back"))
        self.BtnBack2_7.setText(_translate("MainWindow", "Back"))
        self.BtnClr2_2.setText(_translate("MainWindow", "Clear All"))
        self.Image2_2.setText(_translate("MainWindow", "Input Image"))
        self.Classifier_header_2.setText(_translate("MainWindow", "Classifier"))
        self.Result_box_2.setTitle(_translate("MainWindow", "Results"))
        self.label_36.setText(_translate("MainWindow", "Prediction"))
        self.Header3_4.setText(_translate("MainWindow", "Automated Fruit Freshness Recognition System"))
        self.Header3_5.setText(_translate("MainWindow", "Automated Fruit Freshness Recognition System"))
        self.BtnBack2_8.setText(_translate("MainWindow", "Back to Main Window"))
        self.BtnBack2_9.setText(_translate("MainWindow", "Next"))
        self.Header3_6.setText(_translate("MainWindow", "Automated Fruit Freshness Recognition System"))
        self.BtnBack2_10.setText(_translate("MainWindow", "Back to Main Window"))
        self.BtnBack2_11.setText(_translate("MainWindow", "Back"))
        
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    IMAGE_FILE = r'Pic/SplashScreen.png'
    time = 4000

    sg.Window('Window Title', [[sg.Image(IMAGE_FILE)]], transparent_color=sg.theme_background_color(), no_titlebar=True,
              keep_on_top=True).read(timeout=time, close=True)

    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
